#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and "Hi" on the 9th loop

i=1
while [[ $i -le 10 ]]; do
	echo "Best School"
	if [ $i == 9 ]; then
		echo "Hi"
	fi
	(( i += 1))
done
