#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

i=1
while [[ $i -le 10 ]]; do
	echo "Best School"
	if [ $i == 4 ]; then
		echo "bad luck"
	fi
	if [ $i == 8 ]; then
		echo "good luck"
	fi
	(( i += 1))
done
