#!/usr/bin/env bash
# This script displays the content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

for file in *; do
	if [[ ! $file == .* ]]; then
		name=$(echo "$file" | cut -d'-' -f2-)

        echo "$name"
    fi
done
